### ISSUE TITLE
Autoupdate issue

### ISSUE THREAD

**Issue by kijdam** [alinmear/docker-conanexiles#3]
Hi,

First let me thank you for your work on this docker container. It rocks.

I just noticed that whenever an update is pushed on steam the server is not automatically updated.

To have it updating the server I need to remove lastUpdate file in /conanexiles and restart the container.

Anyone else having this issue ?

Thanks !

**Comment by alinmear** [comment]
@kijdam i am facing this problem too. I don't know why but the lastUpdate check is not working. Maybe anybody has an idea what we could check here. I tried to check the 'lastUpdate' value from public branch via steamcmd and also the 'buildid', but none of the them worked so far.

When you want to trigger the update you only need to clear the file lastUpdate, because the controllerscript is checking for a change of the lastUpdate (= buildid) and a new buildid, if they are not the same, an update will be triggered.

So only do something like: echo > /var/lib/docker/volumes/<container>/_data/lastUpdate or echo > <path-to-mount-point>/lastUpdate. After this the Update will be triggered without restarting the container.

**Comment by kijdam** [comment]
@alinmear 
Thanks for your answer. Okay so I'm quite "happy" you have the issue too.

Thanks, I'll take a bit of time to read your script and try to find a way that the check works automatically.

I don't know what you think about it but I would also add a little piece of code to cp -a Saved dir to Saved.timestamp before the update, because I had some surprises the db being wiped/crashed after an update (including the xxxx_backup.db!)

Sounds good to add this ?

**Comment by alinmear** [comment]
@kijdam you can find the update logic here [conanexiles_controller.sh](https://github.com/alinmear/docker-conanexiles/blob/master/files/conanexiles_controller.sh#35-51). If you find a good Solution maybe can you make a pull request for this? 

Regarding the backup logic before an Update: Sounds good to me. I will open a new issue for this and will implement it.

**Comment by alinmear** [comment]
New approach merge with #5. Let's see, hopefuly it works now.

**Comment by alinmear** [comment]
Seems to work. Thanks alot. Closing this issue ...
